<?php
/**
 * @file
 * Creates 
 */

// Alter to turn off memcache

// Create always x/y/z responses

function servicestate_tests_servicestate_services() {
  $services = array();

  $services['removed'] = array(
    'title'         => t('failure'),
    'description'   => 'This should never be run, it should be disabled by servicestate_tests_servicestate_alter.',
    'callback'      => 'failure_function',
    'arguments'     => array(),
    'file'          => null,
    'group'         => '',
    'weight'        => 0,
    'enabled'       => TRUE,
  );

  $services['broken'] = array(
    'title'         => t('Broken service that calls an unreal function'),
    'description'   => t('Checks the memcache daemon is up.'),
    'callback'      => 'failure_function',
    'arguments'     => array(),
    'file'          => null,
    'group'         => '',
    'weight'        => 0,
    'enabled'       => TRUE,
  );

  $services['testvar'] = array(
    'title'         => t('Returns test variable'),
    'description'   => t('Returns the contents of serv_test_var via servicestate_message_variable callback.'),
    'callback'      => 'servicestate_message_variable',
    'arguments'     => array('serv_test_var'),
    'file'          => null,
    'group'         => '',
    'weight'        => 0,
    'enabled'       => TRUE,
  );

  $services['testvar_broken'] = array(
    'title'         => t('Broken callback to servicestate_message_variable'),
    'description'   => t('Attempts to returns the contents of a variable that does not exist.'),
    'callback'      => 'servicestate_message_variable',
    'arguments'     => array('XYZ'),
    'file'          => null,
    'group'         => '',
    'weight'        => 0,
    'enabled'       => TRUE,
  );

  return $services;
  
}

/*
 * Implements hook_servicestate_alter()
 * Used to disable memcache.
 */
function servicestate_tests_servicestate_alter(&$services) {
  $services['memcache']['enabled'] = FALSE;
  $services['removed']['enabled'] = FALSE;
}